baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-csp'

[outputFormats]
  [outputFormats.netlify]
    mediaType = "application/toml"
    baseName = "netlify"
    isPlainText = true
    notAlternative = true
    permalinkable = true
  [outputFormats.server]
    mediaType = "application/toml"
    baseName = "server"
    isPlainText = true
    notAlternative = true
    permalinkable = true

[outputs]
home = ["netlify", "server"]

[params.modules]
[params.modules.mod-one.csp]
    script-src = [
        "'self'",
        "data:",
        "one.com"
    ]

[params.modules.mod-two.csp]
    script-src = [
        "//two.com",
        "https:"
    ]
    style-src = [
        "'self'",
        "'sha256-456'"
    ]

[params.modules.mod-three.csp]
    script-src = [
        "https://three.com"
    ]
    style-src = [
        "'unsafe-inline'",
        "https://style.com",
        "'self'",
        "'sha256-123'"
    ]
    sandbox = [
        "allow-same-origin"
    ]

[params.modules.GoogleAnalytics.csp]
  script-src = [
      "*.google-analytics.com",
      "*.googletagmanager.com"
  ]
  connect-src = [
      "*.google-analytics.com",
      "*.analytics.google.com",
      "*.googletagmanager.com"
  ]
  img-src = [
      "*.google-analytics.com",
      "*.googletagmanager.com"
  ]

[params.headers]
  [params.headers.server]
  [params.headers.netlify]
    source = "netlify.toml"

[module]
  workspace = "mod-csp.work"
  [[module.imports]]
    path = "github.com/gethinode/mod-csp"
  [[module.imports.mounts]]
    source = "data"
    target = "data"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"